version: 1.2
workflows:
- name: PAV2SVs
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/PAV2SVs.wdl
  testParameterFiles:
- name: Resolve
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Resolve.wdl
  testParameterFiles:
- name: TruvariIntrasample
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/TruvariIntrasample.wdl
  testParameterFiles:
- name: Kanpig
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Kanpig.wdl
  testParameterFiles:
- name: Dipcall2SVs
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Dipcall2SVs.wdl
  testParameterFiles:
- name: BuildTrainingResourceIntrasample
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/BuildTrainingResourceIntrasample.wdl
  testParameterFiles:
- name: BuildTrainingResourceIntersample
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/BuildTrainingResourceIntersample.wdl
  testParameterFiles:
