version: 1.2
workflows:
- name: PAV2SVs
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/PAV2SVs.wdl
  testParameterFiles:
- name: Resolve
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Resolve.wdl
  testParameterFiles:
- name: TruvariIntrasample
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/TruvariIntrasample.wdl
  testParameterFiles:
- name: Kanpig
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Kanpig.wdl
  testParameterFiles:
- name: Dipcall2SVs
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Dipcall2SVs.wdl
  testParameterFiles:
- name: BuildTrainingResourceIntrasample
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/BuildTrainingResourceIntrasample.wdl
  testParameterFiles:
- name: BuildTrainingResourceIntersample
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/BuildTrainingResourceIntersample.wdl
  testParameterFiles:
- name: FilterIntrasampleDevPhase2
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/FilterIntrasampleDevPhase2.wdl
  testParameterFiles:
- name: DipcallPhase2
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/DipcallPhase2.wdl
  testParameterFiles:
- name: HGSVC3ExtractHapsFromAssemblies
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/HGSVC3ExtractHapsFromAssemblies.wdl
  testParameterFiles:
- name: Split
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Split.wdl
  testParameterFiles:
- name: HGSVC3Dipcall2BAMs
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/HGSVC3Dipcall2BAMs.wdl
  testParameterFiles:
- name: TruvariIntersamplePhase2
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/TruvariIntersamplePhase2.wdl
  testParameterFiles:
- name: RemoveSamples
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/RemoveSamples.wdl
  testParameterFiles:
- name: KanpigMerged
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/KanpigMerged.wdl
  testParameterFiles:
- name: PasteGTs
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/PasteGTs.wdl
  testParameterFiles:
- name: InterCenterMerge
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/InterCenterMerge.wdl
  testParameterFiles:
- name: InterCenterBench
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/InterCenterBench.wdl
  testParameterFiles:
- name: Workpackage1
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Workpackage1.wdl
  testParameterFiles:
- name: Workpackage2
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Workpackage2.wdl
  testParameterFiles:
- name: Workpackage3
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Workpackage3.wdl
  testParameterFiles:
- name: Workpackage4
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Workpackage4.wdl
  testParameterFiles:
- name: Workpackage5
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Workpackage5.wdl
  testParameterFiles:
- name: Workpackage6
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Workpackage6.wdl
  testParameterFiles:
- name: Workpackage7
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Workpackage7.wdl
  testParameterFiles:
- name: Workpackage8
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Workpackage8.wdl
  testParameterFiles:
- name: Workpackage9
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Workpackage9.wdl
  testParameterFiles:
- name: Workpackage10
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Workpackage10.wdl
  testParameterFiles:
- name: Workpackage11
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Workpackage11.wdl
  testParameterFiles:
- name: Workpackage12
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Workpackage12.wdl
  testParameterFiles:
- name: Workpackage13
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Workpackage13.wdl
  testParameterFiles:
- name: QcPlots
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/QcPlots.wdl
  testParameterFiles:      
- name: PlotHwe
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/PlotHwe.wdl
  testParameterFiles:      
- name: CheckMendelian
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/CheckMendelian.wdl
  testParameterFiles:
- name: BenchCohortSamples
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/BenchCohortSamples.wdl
  testParameterFiles:
- name: GetPresentCalls
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/GetPresentCalls.wdl
  testParameterFiles:
- name: BenchHprcSamples
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/BenchHprcSamples.wdl
  testParameterFiles:
- name: CheckDeNovo
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/CheckDeNovo.wdl
  testParameterFiles:
- name: GetLongCalls
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/GetLongCalls.wdl
  testParameterFiles:
- name: ReadLengthDistribution
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/ReadLengthDistribution.wdl
  testParameterFiles:
- name: SubsampleSimple
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/SubsampleSimple.wdl
  testParameterFiles:
- name: DownloadAssembly
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/DownloadAssembly.wdl
  testParameterFiles:
- name: MapR10Phase2
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/MapR10Phase2.wdl
  testParameterFiles:
- name: MapCCSPhase2Prime
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/MapCCSPhase2Prime.wdl
  testParameterFiles:
- name: MapCCSPhase2
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/MapCCSPhase2.wdl
  testParameterFiles:
- name: AddReadGroup
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/AddReadGroup.wdl
  testParameterFiles:
- name: MapR10Phase2Scattered
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/MapR10Phase2Scattered.wdl
  testParameterFiles:
- name: MapR10Phase2ScatteredLrhq
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/MapR10Phase2ScatteredLrhq.wdl
  testParameterFiles:
- name: PlotHweFocused
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/PlotHweFocused.wdl
  testParameterFiles:
- name: PlotHweFocusedAc
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/PlotHweFocusedAc.wdl
  testParameterFiles:
- name: BenchCohortTrios
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/BenchCohortTrios.wdl
  testParameterFiles:
- name: PlotHweFocusedTruvariCollapse
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/PlotHweFocusedTruvariCollapse.wdl
  testParameterFiles:
- name: Workpackage9Squish
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Workpackage9Squish.wdl
  testParameterFiles:
- name: TestKanpigIntersample
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/TestKanpigIntersample.wdl
  testParameterFiles:
- name: BenchCohortTriosSquish
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/BenchCohortTriosSquish.wdl
  testParameterFiles:
- name: BenchCohortTriosSquish2
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/BenchCohortTriosSquish2.wdl
  testParameterFiles:
- name: GetMapqDistribution
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/GetMapqDistribution.wdl
  testParameterFiles:
- name: Workpackage9Subsets
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Workpackage9Subsets.wdl
  testParameterFiles:
- name: GetGtAdMatrix
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/GetGtAdMatrix.wdl
  testParameterFiles:
- name: AnalyzeGtAdMatrix
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/AnalyzeGtAdMatrix.wdl
  testParameterFiles:
- name: FixUnsupportedGts
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/FixUnsupportedGts.wdl
  testParameterFiles:
- name: GetGenotypingPriors
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/GetGenotypingPriors.wdl
  testParameterFiles:
- name: Workpackage9Palt
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Workpackage9Palt.wdl
  testParameterFiles:
- name: TestBetaBinomial
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/TestBetaBinomial.wdl
  testParameterFiles:
- name: TestBetaBinomial2
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/TestBetaBinomial2.wdl
  testParameterFiles:      
- name: BenchCohortSamplesBetaBinomial
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/BenchCohortSamplesBetaBinomial.wdl
  testParameterFiles:
- name: TestBetaBinomial_Merge
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/TestBetaBinomial_Merge.wdl
  testParameterFiles:      
- name: BenchCohortTriosSquish3
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/BenchCohortTriosSquish3.wdl
  testParameterFiles:
- name: TestBetaBinomial3
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/TestBetaBinomial3.wdl
  testParameterFiles:      
- name: PhabTrios
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/PhabTrios.wdl
  testParameterFiles:      
- name: DeNovoByRegion
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/DeNovoByRegion.wdl
  testParameterFiles:
- name: SubsampleAlignedBam
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/SubsampleAlignedBam.wdl
  testParameterFiles:
- name: FilterTruvariIntersample
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/FilterTruvariIntersample.wdl
  testParameterFiles:
- name: BenchCohortSamples_windowed
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/BenchCohortSamples_windowed.wdl
  testParameterFiles:
- name: FilterTruvariIntersample2
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/FilterTruvariIntersample2.wdl
  testParameterFiles:
- name: SubsetToAncestry
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/SubsetToAncestry.wdl
  testParameterFiles:
- name: BenchCohortTriosSquish4
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/BenchCohortTriosSquish4.wdl
  testParameterFiles:
- name: CountTrSubstratifications
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/CountTrSubstratifications.wdl
  testParameterFiles:
- name: BenchCohortTriosSquish5
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/BenchCohortTriosSquish5.wdl
  testParameterFiles:
- name: GetNCalls
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/GetNCalls.wdl
  testParameterFiles:
- name: GetNCalls2
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/GetNCalls2.wdl
  testParameterFiles:
- name: Bam2Fastq
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Bam2Fastq.wdl
  testParameterFiles:
- name: GetCompositeSvs
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/GetCompositeSvs.wdl
  testParameterFiles:
- name: PersonalizedCohortVcf
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/PersonalizedCohortVcf.wdl
  testParameterFiles:
- name: BenchCohortSamples_PersonalizedCohortVcf
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/BenchCohortSamples_PersonalizedCohortVcf.wdl
  testParameterFiles:
- name: SV_Integration_Workpackage1
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/SV_Integration_Workpackage1.wdl
  testParameterFiles:
- name: SV_Integration_BuildTrainingResource
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/SV_Integration_BuildTrainingResource.wdl
  testParameterFiles:
- name: SV_Integration_Workpackage2
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/SV_Integration_Workpackage2.wdl
  testParameterFiles:
- name: SV_Integration_Workpackage3
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/SV_Integration_Workpackage3.wdl
  testParameterFiles:
- name: SV_Integration_Workpackage5
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/SV_Integration_Workpackage5.wdl
  testParameterFiles:
- name: SV_Integration_Workpackage5_Bnd
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/SV_Integration_Workpackage5_Bnd.wdl
  testParameterFiles:
- name: SV_Integration_Workpackage6
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/SV_Integration_Workpackage6.wdl
  testParameterFiles:
- name: SV_Integration_Workpackage7
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/SV_Integration_Workpackage7.wdl
  testParameterFiles:
- name: SV_Integration_Workpackage8
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/SV_Integration_Workpackage8.wdl
  testParameterFiles:
- name: SV_Integration_RegenotypingAnalysis
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/SV_Integration_RegenotypingAnalysis.wdl
  testParameterFiles:
- name: PhabRegenotypedCohort
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/PhabRegenotypedCohort.wdl
  testParameterFiles:
- name: BuildKanpigHapVcf
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/BuildKanpigHapVcf.wdl
  testParameterFiles:
- name: RegenotypeKanpigHapsVcf
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/RegenotypeKanpigHapsVcf.wdl
  testParameterFiles:
- name: RegenotypeShapeit4
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/RegenotypeShapeit4.wdl
  testParameterFiles:
- name: Trgt2Kanpig
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Trgt2Kanpig.wdl
  testParameterFiles:
