version: 1.2
workflows:
- name: PAV2SVs
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/PAV2SVs.wdl
  testParameterFiles:
- name: Resolve
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Resolve.wdl
  testParameterFiles:
- name: TruvariIntrasample
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/TruvariIntrasample.wdl
  testParameterFiles:
- name: Kanpig
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Kanpig.wdl
  testParameterFiles:
- name: Dipcall2SVs
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Dipcall2SVs.wdl
  testParameterFiles:
- name: BuildTrainingResourceIntrasample
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/BuildTrainingResourceIntrasample.wdl
  testParameterFiles:
- name: BuildTrainingResourceIntersample
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/BuildTrainingResourceIntersample.wdl
  testParameterFiles:
- name: FilterIntrasampleDevPhase2
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/FilterIntrasampleDevPhase2.wdl
  testParameterFiles:
- name: DipcallPhase2
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/DipcallPhase2.wdl
  testParameterFiles:
- name: HGSVC3ExtractHapsFromAssemblies
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/HGSVC3ExtractHapsFromAssemblies.wdl
  testParameterFiles:
- name: Split
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Split.wdl
  testParameterFiles:
- name: HGSVC3Dipcall2BAMs
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/HGSVC3Dipcall2BAMs.wdl
  testParameterFiles:
- name: TruvariIntersamplePhase2
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/TruvariIntersamplePhase2.wdl
  testParameterFiles:
- name: RemoveSamples
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/RemoveSamples.wdl
  testParameterFiles:
- name: KanpigMerged
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/KanpigMerged.wdl
  testParameterFiles:
- name: PasteGTs
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/PasteGTs.wdl
  testParameterFiles:
- name: InterCenterMerge
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/InterCenterMerge.wdl
  testParameterFiles:
- name: InterCenterBench
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/InterCenterBench.wdl
  testParameterFiles:
- name: Workpackage1
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Workpackage1.wdl
  testParameterFiles:
- name: Workpackage2
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Workpackage2.wdl
  testParameterFiles:
- name: Workpackage3
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Workpackage3.wdl
  testParameterFiles:
- name: Workpackage4
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Workpackage4.wdl
  testParameterFiles:
- name: Workpackage5
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Workpackage5.wdl
  testParameterFiles:
- name: Workpackage6
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Workpackage6.wdl
  testParameterFiles:
- name: Workpackage7
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Workpackage7.wdl
  testParameterFiles:
- name: Workpackage8
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Workpackage8.wdl
  testParameterFiles:
- name: Workpackage9
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Workpackage9.wdl
  testParameterFiles:
- name: Workpackage10
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Workpackage10.wdl
  testParameterFiles: