version: 1.2
workflows:
- name: PAV2SVs
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/PAV2SVs.wdl
  testParameterFiles:
- name: Resolve
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Resolve.wdl
  testParameterFiles:
- name: TruvariIntrasample
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/TruvariIntrasample.wdl
  testParameterFiles:
- name: Kanpig
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Kanpig.wdl
  testParameterFiles:
- name: Dipcall2SVs
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Dipcall2SVs.wdl
  testParameterFiles:
- name: BuildTrainingResourceIntrasample
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/BuildTrainingResourceIntrasample.wdl
  testParameterFiles:
- name: BuildTrainingResourceIntersample
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/BuildTrainingResourceIntersample.wdl
  testParameterFiles:
- name: FilterIntrasampleDevPhase2
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/FilterIntrasampleDevPhase2.wdl
  testParameterFiles:
- name: DipcallPhase2
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/DipcallPhase2.wdl
  testParameterFiles:
- name: HGSVC3ExtractHapsFromAssemblies
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/HGSVC3ExtractHapsFromAssemblies.wdl
  testParameterFiles:
- name: Split
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Split.wdl
  testParameterFiles:
- name: HGSVC3Dipcall2BAMs
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/HGSVC3Dipcall2BAMs.wdl
  testParameterFiles:
