#!/bin/bash
#
set -x
WOMTOOL_PATH="/Users/fcunial/apps/cromwell/womtool-84.jar"

java -jar ${WOMTOOL_PATH} validate -l SV_Integration_RegenotypingAnalysis.wdl
java -jar ${WOMTOOL_PATH} validate -l SV_Integration_PlotHwe_SNVs.wdl
java -jar ${WOMTOOL_PATH} validate -l SV_Integration_PlotHwe.wdl
java -jar ${WOMTOOL_PATH} validate -l SV_Integration_Workpackage11.wdl
java -jar ${WOMTOOL_PATH} validate -l SV_Integration_Workpackage10.wdl
java -jar ${WOMTOOL_PATH} validate -l SV_Integration_Workpackage9.wdl
java -jar ${WOMTOOL_PATH} validate -l SV_Integration_Workpackage8_Prime.wdl
java -jar ${WOMTOOL_PATH} validate -l CollapseHapsVcf.wdl
java -jar ${WOMTOOL_PATH} validate -l Trgt2Kanpig.wdl
java -jar ${WOMTOOL_PATH} validate -l SV_Integration_Workpackage7.wdl
java -jar ${WOMTOOL_PATH} validate -l SV_Integration_Workpackage2.wdl
java -jar ${WOMTOOL_PATH} validate -l SV_Integration_Workpackage5.wdl
java -jar ${WOMTOOL_PATH} validate -l SV_Integration_Workpackage3.wdl
java -jar ${WOMTOOL_PATH} validate -l RegenotypeKanpigHapsVcf.wdl
java -jar ${WOMTOOL_PATH} validate -l BuildKanpigHapVcf.wdl
java -jar ${WOMTOOL_PATH} validate -l RegenotypeShapeit4.wdl
java -jar ${WOMTOOL_PATH} validate -l PhabRegenotypedCohort.wdl
java -jar ${WOMTOOL_PATH} validate -l SV_Integration_Workpackage8.wdl
java -jar ${WOMTOOL_PATH} validate -l SV_Integration_Workpackage6.wdl
java -jar ${WOMTOOL_PATH} validate -l SV_Integration_Workpackage5_Bnd.wdl
java -jar ${WOMTOOL_PATH} validate -l SV_Integration_BuildTrainingResource.wdl
java -jar ${WOMTOOL_PATH} validate -l SV_Integration_Workpackage1.wdl
java -jar ${WOMTOOL_PATH} validate -l BenchCohortSamples_PersonalizedCohortVcf.wdl
java -jar ${WOMTOOL_PATH} validate -l HGSVC3Dipcall2BAMs.wdl
java -jar ${WOMTOOL_PATH} validate -l GetCompositeSvs.wdl
java -jar ${WOMTOOL_PATH} validate -l PersonalizedCohortVcf.wdl
java -jar ${WOMTOOL_PATH} validate -l Bam2Fastq.wdl
java -jar ${WOMTOOL_PATH} validate -l GetNCalls2.wdl
java -jar ${WOMTOOL_PATH} validate -l GetNCalls.wdl
java -jar ${WOMTOOL_PATH} validate -l BenchCohortTriosSquish5.wdl
java -jar ${WOMTOOL_PATH} validate -l CountTrSubstratifications.wdl
java -jar ${WOMTOOL_PATH} validate -l BenchCohortTriosSquish4.wdl
java -jar ${WOMTOOL_PATH} validate -l SubsetToAncestry.wdl
java -jar ${WOMTOOL_PATH} validate -l FilterTruvariIntersample2.wdl
java -jar ${WOMTOOL_PATH} validate -l BenchCohortSamples_windowed.wdl
java -jar ${WOMTOOL_PATH} validate -l FilterTruvariIntersample.wdl
java -jar ${WOMTOOL_PATH} validate -l BenchCohortTriosSquish3.wdl
java -jar ${WOMTOOL_PATH} validate -l MapCCSPhase2.wdl
java -jar ${WOMTOOL_PATH} validate -l MapCCSPhase2Prime.wdl
java -jar ${WOMTOOL_PATH} validate -l MapR10Phase2.wdl
java -jar ${WOMTOOL_PATH} validate -l SubsampleAlignedBam.wdl
java -jar ${WOMTOOL_PATH} validate -l Workpackage9Squish.wdl
java -jar ${WOMTOOL_PATH} validate -l DeNovoByRegion.wdl
java -jar ${WOMTOOL_PATH} validate -l PhabTrios.wdl
java -jar ${WOMTOOL_PATH} validate -l TestKanpigIntersample.wdl
java -jar ${WOMTOOL_PATH} validate -l TestBetaBinomial3.wdl
java -jar ${WOMTOOL_PATH} validate -l TestBetaBinomial_Merge.wdl
java -jar ${WOMTOOL_PATH} validate -l BenchCohortSamplesBetaBinomial.wdl
java -jar ${WOMTOOL_PATH} validate -l TestBetaBinomial2.wdl
java -jar ${WOMTOOL_PATH} validate -l TestBetaBinomial.wdl
java -jar ${WOMTOOL_PATH} validate -l Workpackage9Palt.wdl
java -jar ${WOMTOOL_PATH} validate -l GetGenotypingPriors.wdl
java -jar ${WOMTOOL_PATH} validate -l FixUnsupportedGts.wdl
java -jar ${WOMTOOL_PATH} validate -l AnalyzeGtAdMatrix.wdl
java -jar ${WOMTOOL_PATH} validate -l GetGtAdMatrix.wdl
java -jar ${WOMTOOL_PATH} validate -l Workpackage9Subsets.wdl
java -jar ${WOMTOOL_PATH} validate -l GetMapqDistribution.wdl
java -jar ${WOMTOOL_PATH} validate -l BenchCohortTriosSquish2.wdl
java -jar ${WOMTOOL_PATH} validate -l BenchCohortTriosSquish.wdl
java -jar ${WOMTOOL_PATH} validate -l PlotHweFocusedTruvariCollapse.wdl
java -jar ${WOMTOOL_PATH} validate -l BenchCohortTrios.wdl
java -jar ${WOMTOOL_PATH} validate -l PlotHweFocusedAc.wdl
java -jar ${WOMTOOL_PATH} validate -l BenchCohortSamples.wdl
java -jar ${WOMTOOL_PATH} validate -l PlotHweFocused.wdl
java -jar ${WOMTOOL_PATH} validate -l MapR10Phase2ScatteredLrhq.wdl
java -jar ${WOMTOOL_PATH} validate -l MapR10Phase2Scattered.wdl
java -jar ${WOMTOOL_PATH} validate -l AddReadGroup.wdl
java -jar ${WOMTOOL_PATH} validate -l DownloadAssembly.wdl
java -jar ${WOMTOOL_PATH} validate -l SubsampleSimple.wdl
java -jar ${WOMTOOL_PATH} validate -l ReadLengthDistribution.wdl
java -jar ${WOMTOOL_PATH} validate -l GetLongCalls.wdl
java -jar ${WOMTOOL_PATH} validate -l CheckDeNovo.wdl
java -jar ${WOMTOOL_PATH} validate -l BenchHprcSamples.wdl
java -jar ${WOMTOOL_PATH} validate -l GetPresentCalls.wdl
java -jar ${WOMTOOL_PATH} validate -l InterCenterMerge.wdl
java -jar ${WOMTOOL_PATH} validate -l CheckMendelian.wdl
java -jar ${WOMTOOL_PATH} validate -l PlotHwe.wdl
java -jar ${WOMTOOL_PATH} validate -l QcPlots.wdl
java -jar ${WOMTOOL_PATH} validate -l Workpackage13.wdl
java -jar ${WOMTOOL_PATH} validate -l Workpackage12.wdl
java -jar ${WOMTOOL_PATH} validate -l Workpackage11.wdl
java -jar ${WOMTOOL_PATH} validate -l Workpackage10.wdl
java -jar ${WOMTOOL_PATH} validate -l Workpackage9.wdl
java -jar ${WOMTOOL_PATH} validate -l Workpackage8.wdl
java -jar ${WOMTOOL_PATH} validate -l Workpackage7.wdl
java -jar ${WOMTOOL_PATH} validate -l Workpackage6.wdl
java -jar ${WOMTOOL_PATH} validate -l Workpackage5.wdl
java -jar ${WOMTOOL_PATH} validate -l Workpackage4.wdl
java -jar ${WOMTOOL_PATH} validate -l Workpackage3.wdl
java -jar ${WOMTOOL_PATH} validate -l Workpackage2.wdl
java -jar ${WOMTOOL_PATH} validate -l Workpackage1.wdl
java -jar ${WOMTOOL_PATH} validate -l InterCenterBench.wdl
java -jar ${WOMTOOL_PATH} validate -l PasteGTs.wdl
java -jar ${WOMTOOL_PATH} validate -l KanpigMerged.wdl
java -jar ${WOMTOOL_PATH} validate -l RemoveSamples.wdl
java -jar ${WOMTOOL_PATH} validate -l TruvariIntersamplePhase2.wdl
java -jar ${WOMTOOL_PATH} validate -l Split.wdl
java -jar ${WOMTOOL_PATH} validate -l HGSVC3ExtractHapsFromAssemblies.wdl
java -jar ${WOMTOOL_PATH} validate -l DipcallPhase2.wdl
java -jar ${WOMTOOL_PATH} validate -l FilterIntrasampleDevPhase2.wdl
java -jar ${WOMTOOL_PATH} validate -l Kanpig.wdl
java -jar ${WOMTOOL_PATH} validate -l TruvariIntrasample.wdl
java -jar ${WOMTOOL_PATH} validate -l Resolve.wdl
java -jar ${WOMTOOL_PATH} validate -l PAV2SVs.wdl
