import java.util.*;
import java.io.*;


/**
 * Given two clip files generated by `UltralongIntervalGetClips.java`, one for 
 * the left breakpoint and one for the right breakpoint of a given SV interval,
 * the program returns the number of alignments in each file such that:
 *
 * (1) there is an alignment with the same read ID in the other file;
 *
 * (2) like (1), and moreover the maximal points of the two alignments are 
 * adjacent in read coordinates.
 */
public class UltralongIntervalIntersectClips {
    
    /**
     * @param args 
     * 0,3: assumed to be sorted by read ID.
     */
    public static void main(String[] args) throws IOException {
        final String CLIPS1_FILE = args[0];
        final int N_CLIPS1 = Integer.parseInt(args[1]);
        final boolean CLIPS1_IS_LEFT_MAXIMAL = Integer.parseInt(args[2])==1;
        final String CLIPS2_FILE = args[3];
        final int N_CLIPS2 = Integer.parseInt(args[4]);
        final boolean CLIPS2_IS_LEFT_MAXIMAL = Integer.parseInt(args[5])==1;
        final int ADJACENCY_SLACK_BP = Integer.parseInt(args[6]);
        
        boolean isRc1, isRc2;
        int i, j, k, n10, n11, n20, n21;
        int readPos1, readPos2, readLength1, readLength2;
        String str, readId1, readId2;
        BufferedReader br;
        boolean[][] marked1, marked2;
        String[][] clips1, clips2;
        
        // Returning immediately if the input files are empty
        n10=0; n11=0; n20=0; n21=0;
        if (N_CLIPS1==0 || N_CLIPS2==0) {
            System.out.println(n10+","+n11+","+n20+","+n21);
            System.exit(0);
        }
        
        // Loading both files
        clips1 = new String[N_CLIPS1][4]; marked1 = new boolean[2][N_CLIPS1];
        br = new BufferedReader(new InputStreamReader(new FileInputStream(CLIPS1_FILE)));
        str=br.readLine(); i=-1;
        while (str!=null) {
            clips1[++i]=str.split("\t");
            str=br.readLine();
        }
        br.close();
        clips2 = new String[N_CLIPS2][4]; marked2 = new boolean[2][N_CLIPS2];
        br = new BufferedReader(new InputStreamReader(new FileInputStream(CLIPS2_FILE)));
        str=br.readLine(); i=-1;
        while (str!=null) {
            clips2[++i]=str.split("\t");
            str=br.readLine();
        }
        br.close();
        
        // Naive implementation (all pairwise comparisons).
        Arrays.fill(marked1[0],false); Arrays.fill(marked1[1],false); 
        Arrays.fill(marked2[0],false); Arrays.fill(marked2[1],false);
        j=0;
        for (i=0; i<N_CLIPS1; i++) {
            readId1=clips1[i][0];
            isRc1=clips1[i][1].charAt(0)=='1';
            readPos1=Integer.parseInt(clips1[i][2]);
            readLength1=Integer.parseInt(clips1[i][3]);
            for (; j<N_CLIPS2; j++) {
                readId2=clips2[j][0];
                k=readId2.compareTo(readId1);
                if (k<0) continue;
                else if (k>0) break;
                marked1[0][i]=true; marked2[0][j]=true;
                isRc2=clips2[j][1].charAt(0)=='1';
                readPos2=Integer.parseInt(clips2[j][2]);
                readLength2=Integer.parseInt(clips2[j][3]);
                if (areAdjacent(isRc1,readPos1,readLength1,CLIPS1_IS_LEFT_MAXIMAL,isRc2,readPos2,readLength2,CLIPS2_IS_LEFT_MAXIMAL,ADJACENCY_SLACK_BP)) { marked1[1][i]=true; marked2[1][j]=true; }
            }
        }
        
        // Outputting
        for (i=0; i<N_CLIPS1; i++) {
            if (marked1[0][i]) n10++;
        }
        for (i=0; i<N_CLIPS1; i++) {
            if (marked1[1][i]) n11++;
        }
        for (i=0; i<N_CLIPS2; i++) {
            if (marked2[0][i]) n20++;
        }
        for (i=0; i<N_CLIPS2; i++) {
            if (marked2[1][i]) n21++;
        }
        System.out.println(n10+","+n11+","+n20+","+n21);
    }
    
    
    /**
     * @return TRUE iff two maximal alignments of the same read are such that 
     * their maximal endpoints are adjacent on the read.
     */
    private static final boolean areAdjacent(boolean isRc1, int pos1, int length1, boolean isLeftMaximal1, boolean isRc2, int pos2, int length2, boolean isLeftMaximal2, int slack) {
        if (!isRc1) {
            if (isLeftMaximal1) {
                if (isLeftMaximal2) return isRc2 && (length2-pos2<=pos1+slack && length2-pos2>=pos1-slack);
                else return !isRc2 && pos2<=pos1+slack && pos2>=pos1-slack;
            }
            else {
                if (isLeftMaximal2) return !isRc2 && pos2<=pos1+slack && pos2>=pos1-slack;
                else return isRc2 && (length2-pos2<=pos1+slack && length2-pos2>=pos1-slack);
            }
        }
        else {
            if (isLeftMaximal1) {
                if (isLeftMaximal2) return !isRc2 && (pos2<=length1-pos1+slack && pos2>=length1-pos1-slack);
                else return isRc2 && pos2<=pos1+slack && pos2>=pos1-slack;
            }
            else {
                if (isLeftMaximal2) return isRc2 && pos2<=pos1+slack && pos2>=pos1-slack;
                else return !isRc2 && (pos2<=length1-pos1+slack && pos2>=length1-pos1-slack);
            }
        }
    }

}